import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Headers from "@/components/headers";
import PageTransitions from "@/components/Pagetransitions";
import StairTransitions from "@/components/stairTransitions";

// শুধু JetBrains Mono ফন্ট
const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-jetbrainsMono',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={jetBrainsMono.variable}>
      <body
        className={`${jetBrainsMono.variable} antialiased bg-primary text-white`}
      >
        <Headers />
        <StairTransitions />
        <PageTransitions>
          {children}
        </PageTransitions>
      </body>
    </html>
  );
}
