import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Headers from "@/components/headers";
import PageTransitions from "@/components/Pagetransitions";
import StairTransitions from "@/components/stairTransitions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primary text-white `}
      >
        <Headers />
        
       
        <StairTransitions />
        
    
        <PageTransitions>
          {children}
        </PageTransitions>
      </body>
    </html>
  );
}